build:
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - docker version
    - docker-compose version
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up -d

golang:
  image: golang
  stage: test
  script:
    - go test -v ./...
  artifacts:
    when: always
    reports:
      junit: report.xml
