image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose -f docker-compose-tests.yml build
    - docker-compose up -d

test:
  stage: test
  script:
    - docker-compose -f docker-compose-tests.yml build
    - docker-compose -f docker-compose-tests.yml up --abort-on-container-exit
    # shutdown tests ran separately, as they'll end in services shutting down
    - docker-compose -f docker-compose-tests-shutdown.yml build
    - docker-compose -f docker-compose-tests-shutdown.yml up --abort-on-container-exit

# build and deploy a clean environment after tests
deploy:
  stage: production
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up -d