image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose -f docker-compose-tests.yml build
    - docker-compose up -d

test:
  stage: test
  script:
    - docker-compose build
    - docker-compose -f docker-compose-tests.yml up -d --abort-on-container-exit