version: '3.8'

services:

  rabbitmq:
    networks:
      - devops
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672

  orig:
    networks:
      - devops
    build:
      context: ./
      dockerfile: orig/Dockerfile
    container_name: orig
    depends_on:
      - rabbitmq
      - server

  imed:
    networks:
      - devops
    build:
      context: ./
      dockerfile: ./imed/Dockerfile
    container_name: imed
    depends_on:
      - rabbitmq

  obse:
    networks:
      - devops
    build:
      context: ./
      dockerfile: ./obse/Dockerfile
    container_name: obse
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq

  httpserv:
    networks:
      - devops
    build:
      context: ./
      dockerfile: ./httpserv/Dockerfile
    container_name: httpserv
    expose:
      - 80
    volumes:
      - ./data:/app/data

  server:
    networks:
      - devops
    build:
      context: ./
      dockerfile: server/Dockerfile
    container_name: server
    ports:
      - 8081:80
    expose:
      - 80
    depends_on:
      - httpserv
    volumes:
      - ./data:/app/data


networks:
  devops:
    driver: bridge